# sprint12/add-most-populars

###
# group: users
# @name User create
POST {{baseUrl}}/users
Content-Type: application/json
Accept: */*

{
  "login": "dolore",
  "name": "Nick Name",
  "email": "mail@mail.ru",
  "birthday": "1946-08-20"
}

> {%
    // TODO: migrate to HTTP Client Response handler API
    // pm.test("Status code is 200 or 201", function () {

    //     pm.expect(pm.response.code).to.be.oneOf([200,201]);

    // });

    // pm.test("Has user create response", function () {

    //     pm.response.to.be.withBody;

    //     pm.response.to.be.json;

    // });

    // pm.test("Test user 'id' field", function () {

    //     var jsonData = pm.response.json();

    //     pm.expect(jsonData).to.have.property('id');

    //     pm.expect(jsonData.id, '"id" must be 1').to.eql(1);

    // });

    // pm.test("Test user 'email' field", function () {

    //     var jsonData = pm.response.json();

    //     pm.expect(jsonData).to.have.property('email');

    //     pm.expect(jsonData.email, '"email" must be "mail@mail.ru"').to.eql('mail@mail.ru');

    // });

    // pm.test("Test user 'name' field", function () {

    //     var jsonData = pm.response.json();

    //     pm.expect(jsonData).to.have.property('name');

    //     pm.expect(jsonData.name, '"name" must be "Nick Name"').to.eql('Nick Name');

    // });

    // pm.test("Test user 'login' field", function () {

    //     var jsonData = pm.response.json();

    //     pm.expect(jsonData).to.have.property('login');

    //     pm.expect(jsonData.login, '"login" field must be "dolore"').to.eql('dolore');    

    // });

    // pm.test("Test user 'birthday' field", function () {

    //     var jsonData = pm.response.json();

    //     pm.expect(jsonData).to.have.property('birthday');

    //     pm.expect(jsonData.birthday, '"birthday" field must be "1946-08-20"').to.eql('1946-08-20');

    // });
%}

###